data:
  center_pos_noise: true
  center_pos_noise_std: 5.0
  val_csv_path: ${oc.env:BASE_PATH}/data/receptor_data/metadata_test.csv
defaults:
- eval
- _self_
experiment:
  eval_batch_size: 8
  eval_ckpt_path: ${oc.env:BASE_PATH}/experiments/checkpoints/diffpepbuilder_v1.pth
  eval_dir: ${oc.env:BASE_PATH}/runs
  name: inference
  num_gpus: 8
  num_loader_workers: 4
  use_ddp: true
  use_gpu: true
inference:
  denoising:
    min_t: 0.01
    noise_scale: 1.0
    num_t: 200
  sampling:
    max_length: 16
    min_length: 12
    samples_per_length: 4
    seq_temperature: 0.1
  save_traj: false
  seed: 42
  ss_bond:
    build_ss_bond: true
    entropy_threshold: 0.01
    frag_lib_path: ${oc.env:BASE_PATH}/SSbuilder/SSBLIB
    max_ss_bond: 2
    save_entropy: true
